### ISSUE TITLE
希望大佬能给个比较好的readme方便我们这些小喽啰能读懂 

### ISSUE THREAD

**Issue by Cinux-Chosan** [lujqme/proxy_pool#24]

**Comment by Cinux-Chosan** [comment]
建议以 url  scheme 作为  mongo#_id , 这样就不会插入相同的记录了.. 由于代理好像没有检测可用性我就自己写了一个, 在本地测试的时候会插入多条相同记录, 并且定时执行的时候也会插入很多相同记录, 不知这一点大佬可否认同..

**Comment by lujqme** [comment]
这个项目其实是个标准的scrapy项目，我看了下你的技能栈，可能没涉及scrapy相关的内容。针对你说的去重这个问题，可以修改pipeline.py中第30行部分，建议是采用上文的第二个方案，就是判断不存在再insert。可以参考 https://api.mongodb.com/python/current/tutorial.html
